# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20170708_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='browser',
        ),
        migrations.DeleteModel(
            name='Browser',
        ),
    ]
